name: Push as Owner for Vercel Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  re-push-as-owner:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git user
        run: |
          git config --global user.name "Arnav-2004"
          git config --global user.email "arnavrangwani@gmail.com"

      - name: Push as owner
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          git push origin main
